#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint the repo
yarn turbo run lint:fix --filter="[HEAD^1]" --filter=@inno/gql

# test the repo
yarn turbo run test --filter="[HEAD^1]" --filter=@inno/gql
