name: BACKEND_CI

on:
  push:
    branches: ['main']
    paths:
      - 'apps/backend/**'
      - 'packages/api-contracts/**'
      - 'packages/constants/**'
      - 'packages/db-schema/**'
      - 'packages/utils/**'
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test Backend App
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm turbo run typecheck --filter=@inno/backend...

      - name: Build
        run: pnpm turbo run build --filter=@inno/backend...

      - name: Test
        run: pnpm turbo run test --filter=@inno/backend...
